version: '3.9'

services:
  es8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: es8
    environment:
      - node.name=es8
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib8:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: kib8
    environment:
      - node.name=kib8
      - cluster.name=es-docker-cluster
      - ELASTICSEARCH_HOSTS=http://es8:9200
    volumes:
      - kibanadata:/usr/share/kibana/data
      
    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on:
      - es8
  
  sonarqube:
    image: sonarqube:community
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/sonarqube_extensions
      - sonarqube_logs:/opt/sonarqube/sonarqube_logs
    ports:
      - "9000:9000"

  jenkins:
    image: jenkins/jenkins:2.479.1-jdk17
    ports:
      - "8080:8080"
    volumes:
      #- jenkins-vol:/var/jenkins_home
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      #- /usr/bin/docker:/usr/bin/docker
      #- /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    environment:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_TLS_CERTDIR: "" 
    networks:
      - elastic
    depends_on:
      - docker

  docker:
    image: docker:20.10.7-dind
    privileged: true  
    ports:
      - "2375:2375"  
    networks:
      - elastic

  
  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.3
    container_name: logstash
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - /Users/akshatha/Desktop/Personal_repo/CICD-ETL-Pipeline/data:/data  # Mount your data directory

    ports:
      - "9600:9600"
    networks:
      - elastic
    depends_on:
      - es8

volumes:
  esdata:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  jenkins-vol:
  kibanadata:
    
networks:
  elastic:
    #driver: bridge
